Use echo instead of printf to slightly improve performance, use tabs instead of spaces, improved the handling of variables
Signed-off-by: Johnothan King <johnothanking@protonmail.com>

diff --git a/3dsmicrosd b/3dsmicrosd
--- a/3dsmicrosd
+++ b/3dsmicrosd
@@ -22,45 +22,46 @@
 #
 
 # The version of the script
-SCRIPTVER=1.1.0
+SCRIPTVER=1.2.0
 
 # Print and read
-pread() {
-    printf "$1\n"
-    read $2
+eread() {
+	echo "$1"
+	read $2
 }
 
-printf "3dsmicrosd version $SCRIPTVER\n"
-pread "Enter the username used for microSD management on the New 3DS..." n3dsusr
-pread "Enter the name the New 3DS uses for microSD management..." n3dsname
-pread "Enter the New 3DS' local IP address..." n3dsip
-pread "Where would you like to mount your microSD card? (e.g. /mnt)..." n3dsmnt
+echo  "3dsmicrosd version $SCRIPTVER\n"
+eread "Enter the username used for microSD management on the New 3DS..." n3dsusr
+eread "Enter the name the New 3DS uses for microSD management..." n3dsname
+eread "Enter the New 3DS' local IP address..." n3dsip
+eread "Where would you like to mount your microSD card? (e.g. /mnt)..." n3dsmnt
 
 # Mount the microSD card
 sudo mkdir -p "$n3dsmnt"
-sudo mount -t cifs //"$n3dsname"/microSD "$n3dsmnt" -o user="$n3dsusr",ip=$n3dsip,servern="$n3dsname",uid=`sudo -u \`whoami\` id -u`,gid=`sudo -u \`whoami\` id -g`,nounix,vers=1.0
+sudo mount -t cifs "//$n3dsname/microSD" "$n3dsmnt" -o "user=$n3dsusr,ip=$n3dsip,servern=$n3dsname,uid=`sudo -u \`whoami\` id -u`,gid=`sudo -u \`whoami\` id -g`,nounix,vers=1.0"
+echo ""
 
 # Check to see if the mount was successful
 if [ -d "$n3dsmnt/Nintendo 3DS" ]; then
-    printf "\nThe New 3DS' microSD card is now mounted at $n3dsmnt\n"
 
-    # Allow the user to use a shell for transferring files
-    printf "Which shell would you like to use (e.g. /bin/bash)? This will allow you to transfer your files between your PC and 3DS...\n"
-    while true; do
-        read n3dsshell
-        if [ -x "$n3dsshell" ]; then
-            $n3dsshell
-            break
-        else
-            printf "Please select a valid shell...\n"
-        fi
-    done
+	# Allow the user to use a shell for transferring files
+	echo "The New 3DS' microSD card is now mounted at $n3dsmnt"
+	echo "Which shell would you like to use (e.g. /bin/bash)? This will allow you to transfer your files between your PC and 3DS..."
+	while true; do
+		read n3dsshell
+		if [ -x "$n3dsshell" ]; then
+			$n3dsshell
+			break
+		else
+			echo "Please select a valid shell..."
+		fi
+	done
 
-    # Unmount the microSD card when done
-    sync
-    sudo umount -R "$n3dsmnt"
-    exit 0
+	# Unmount the microSD card when done
+	sync
+	sudo umount -R "$n3dsmnt"
+	exit 0
 else # If it failed
-    printf "\nThe microSD card failed to mount!\n"
-    exit 1
+	echo "The microSD card failed to mount!"
+	exit 1
 fi
