Version 1.2.2: Use tabs instead of spaces to decrease file size, single quotes are now used for strings that use !
Signed-off-by: Johnothan King <johnothanking@protonmail.com>

diff --git a/3dsmicrosd b/3dsmicrosd
--- a/3dsmicrosd
+++ b/3dsmicrosd
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# Copyright (c) 2016-2018 Johnothan King
+# Copyright (c) 2016-2019 Johnothan King
 #
 # Permission is hereby granted, free of charge, to any person obtaining a copy
 # of this software and associated documentation files (the "Software"), to deal
@@ -22,12 +22,12 @@
 #
 
 # The version of the script
-SCRIPTVER=1.2.1
+SCRIPTVER=1.2.2
 
 # Print and read
 eread() {
-    echo "$1"
-    read $2
+	echo "$1"
+	read $2
 }
 
 echo  "3dsmicrosd version $SCRIPTVER"
@@ -45,24 +45,24 @@ echo ""
 # Check to see if the mount was successful
 if [ -d "$n3dsmnt/Nintendo 3DS" ]; then
 
-    # Allow the user to use a shell for transferring files
-    echo "The New 3DS' microSD card is now mounted at $n3dsmnt"
-    echo "Which shell would you like to use (e.g. /bin/bash)? This will allow you to transfer your files between your PC and 3DS..."
-    while true; do
-        read n3dsshell
-        if [ -x "$n3dsshell" ]; then
-            $n3dsshell
-            break
-        else
-            echo "Please select a valid shell..."
-        fi
-    done
+	# Allow the user to use a shell for transferring files
+	echo "The New 3DS' microSD card is now mounted at $n3dsmnt"
+	echo "Which shell would you like to use (e.g. /bin/bash)? This will allow you to transfer your files between your PC and 3DS..."
+	while true; do
+		read n3dsshell
+		if [ -x "$n3dsshell" ]; then
+			$n3dsshell
+			break
+		else
+			echo "Please select a valid shell..."
+		fi
+	done
 
-    # Unmount the microSD card when done
-    sync
-    sudo umount -R "$n3dsmnt"
-    exit 0
+	# Unmount the microSD card when done
+	sync
+	sudo umount -R "$n3dsmnt"
+	exit 0
 else # If it failed
-    echo "The microSD card failed to mount!"
-    exit 1
+	echo 'The microSD card failed to mount!'
+	exit 1
 fi
